package scenes;

public enum Scenes {
    ARCADE_BATTLE,
    ARCADE_CHARACTER_SELECT,
    ARCADE_GAME_OVER,
    ARCADE_LEVEL_SELECT,
    ARCADE_NAME_INPUT,
    ARCADE_LEADERBOARD,
    PVP_BATTLE,
    PVP_CHARACTER_SELECT,
    PVP_STAGE_SELECT,
    VS_AI_BATTLE,
    VS_AI_CHARACTER_SELECT,
    VS_AI_STAGE_SELECT,
    MAIN_MENU,
    MODE_SELECT
}
